version: "3.9"
services:
  zookeeper:
    restart: always
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      surfer:

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9091:9091
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, LOCAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092, LOCAL://localhost:9091
      KAFKA_LISTENERS: LOCAL://:9091, INTERNAL://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      surfer:

#  kafka2:
#    image: confluentinc/cp-kafka:latest
#    restart: always
#    depends_on:
#      - zookeeper
#    ports:
#      - 29093:29092
#    hostname: kafka2
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#    networks:
#      surfer:

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092,kafka2:29093
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
#      - kafka2
      - zookeeper
    networks:
      surfer:

  surfer-gateway:
    image: pron9/candle-kafka-producer:1.0.3
    container_name: gateway

  candle-producer:
    image: pron9/candle-kafka-producer:1.0.3
    container_name: producer
    ports:
      - 8080:7777
    links:
      - kafka-ui
    depends_on:
      - surfer-gateway
    environment:
#    следует учитывать, что в приложени время по UTC
      - hours-to-subtract=5
    networks:
      surfer:

  ema-kafka-consumer:
    restart: always
    image: pron9/ema-kafka-consumer:1.0.0
    environment:
      - broker.base.url=http://producer
      - broker.port=7777
    ports:
      - 8081:7778
    links:
      - kafka-ui
      - candle-producer
    depends_on:
      - candle-producer
      - surfer-gateway

#  prometheus:
#    image: prom/prometheus
#    ports:
#      - 9090:9090
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
#    networks:
#      surfer:

#  grafana:
#    image: grafana/grafana
#    restart: always
#    container_name: grafana
#    ports:
#      - 8070:3000
#    networks:
#      surfer:
#  consumer:
#    image: pron9/kafka-consumer:1.0.1
#    ports:
#      - 8081:8080
#    links:
#      - kafka-ui

  db:
    image: mysql:8.3.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: WOwnib846
    ports:
      - 3306:3306
    volumes:
      - ./mysql/8.3.0:/var/lib/mysql
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 3307:8080

networks:
  surfer:
    driver:
      bridge